### ISSUE TITLE
Some UI labels are not translatable. 

### ISSUE THREAD

**Issue by dev-0x7C6** [minswap/minswap-translation#14]
Some of UI labels missing translations or are not translatable.

![no_translations_for_2nd](https://user-images.githubusercontent.com/12091654/152035917-25cfabee-ac0a-417b-ac75-0f180abfa812.png)
![no_translations_for_3](https://user-images.githubusercontent.com/12091654/152035928-c23ca404-e10a-4754-bba0-14dc9d8a4286.png)
![no_translations_for](https://user-images.githubusercontent.com/12091654/152035938-e2a0744d-47b6-4ecb-aa99-9ddf598a920c.png)

**Comment by longngn** [comment]
@theuranus is this solved yet?

**Comment by theuranus** [comment]
It's solved
